let ar = {
    "aboutMsg": "اتقدم بالشكر الجزيل لمن قام بمساعدتي في اتمام هذا البوت شكراً لكم جميعاً \n%credit%\n مبرمج البوت @rrbot\n قناة البوتات @botar \n /start - للرجوع للقائمة الرئيسية",
    "about": "عن البوت",
    "title1": "🔒 هذه همسة سرية الى ",
    "title2": " هو فقط من يستطيع رؤيتها",
    "showMsg": "اظهار الرسالة 🔐",
    "missingInfo": "اكتب الهمسة ثم معرف الشخص المهموس لهُ كما في المثال",
    "missingMessage": "الرسالة غير متوفرة",
    "mismatchMessageRecipient": "nice Try...",
    "howToUseButton": "طريقة الاستخدام . . .",
    "howToNoUsername": "كيف ارسل لمن لا يملك معرف؟",
    "switch_inline_query": "السلام عليكم @abdood",
    "switch_pm_text": "تعلم ارسال رسالة سرية",
    "notToU": "ناسف, لا يمكنك رؤية هذه الهمسة لانها غير موجهة لك 🔒.",
    "description": "@nnbbot 'الرسالة التي يراها الطرف الثاني' @username",
    "description2": "هو فقط من سيتمكن من رؤيتها",
    "queryTooLong": "الرسالة طويلة جداً 🤕",
    "queryTooLongDescription": "اقصى حد لطول الرسالة هو 200 حرف",
    "startBtn": "طرق اخرى للاستخدام 📝",
    "testItNow": "جربهُ الان",
    "testItNowInline": "\nالسلام عليكم هذه همسة\n@abdood",
    "websiteLink": "شرح مفصل",
    "id": "ايدي المستخدم",
    "firstName": "الاسم الاول",
    "lastName": "الاسم الاخير",
    "username": "المعرف",
    "sendUsingId": "ارسال همسة باستخدام الايدي",
    "test": "هذه همسة تجريبية",
    "sendUsingUsername": "ارسال همسة باستخدام المعرف",
    "fwd": "لارسال رسالة سرية لهذا المستخدم اضغط على الزر ادناه ثم اختر المجموعة التي يتواجد فيها هذا المستخدم",
    "dontFwdChannel": "هذه الرسالة محولة من قناة \n قم بتحويل رسالة من حساب موجود معك في اي مجموعة حتى ترسل له همسة\n /start - تعلم طريقة الاستخدام",
    "noUsername": "\n\t\t🤔 كيف ارسل همسة لمن لا يمتلك معرف؟\n\n\t\t💡 يمكنك استخدام ايدي المستخدم بدلا من المعرف وهذه الطريقة تعمل مع كل الناس سواء كان عندهم معرف ام لا.\n\n\t\t🤔 تمام الان ما هو ايدي المستخدم؟\n\n\t\t💡 ايدي المستخدم هو رقم يمثل تسلسل الحساب, ويوجد لكل حساب ايدي خاص به\n\n\t\t🤔 كيف استخرج ايدي الشخص الذي اريد ان ارسل له همسة؟\n\n\t\t💡 لاستخراج ايدي الشخص قم بتحويل اي رسالة من هذا الشخص الى هنا وانا سوف اعطيك الايدي.\n\n\t\t🤔 طيب الان انا حصلت على الايدي. كيف ارسل همسة لهذا الايدي؟\n\n\t\t💡 الموضوع بسيط جداً, تقوم بوضع ايدي الشخص المهموس له في نهاية الرسالة كما في هذا المثال \n\t\t`@nnbbot hello 12345678`\n\t\t\n\t\tحيث ان الرقم الموجود في هذا المثال يمثل ايدي الشخص المهموس له\n\n\t\t🤷‍♂️ان واجهتك مشاكل في تطبيق هذا الشرح اضغط على `شرح مفصل`",
    "start": "\nمرحباً: @x! \n🌐 انا بوت اهمسلي.\n\n💬 يمكنك استخدامي لارسال رسائل سرية (همسات) في اي مجموعة تشاء.\n\t\t\n🔮 انا اعمل عن بعد, هذا يعني انك تستيط استخدامي دون الحاجة لوجودي في المجموعة.\n\n💌 طريقة استخدامي سهلة جداً, قم بتحويل اي رسالة من الشخص الذي تريد ان تهمس له هنا\n\nهناك طرق اخرى للاستخدام يمكنك رؤيتها عبر الضغط على `طرق اخرى لاستخدام البوت`\n[💎 اضغط هنا واحصل على بوتات رائعة مجاناً 💎](https://t.me/+erdi3TX590hlNWVi)\n",
    "howToUse": "طريقة الاستخدام الثانية📝\n\nيجب كتابة الامر بهذه الصيغة حتى يعمل البوت بشكل صحيح\n\n`@nnbbot رسالتك @username`\n\nالان ساقسم هذه الصيغة الى 3 اجزاء واشرح عمل كل جزء:-\n\na- `@nnbbot`\nمعرف البوت يكتب في بداية الرسالة حتى يتم استدعاء البوت.\nb- `رسالتك`\nهي الرسالة السرية (الهمسة) التي ستقوم بارسالها.\nc- `@username`\nمعرف الشخص المهموس لهُ\nقم بتبديل هذا بمعرف الشخص الذي تريد ان تهمس لهُ.\n\nمثال:-\n`@nnbbot السلام عليكم هذه همسة @abdood` \n\n📎 البوت يعمل في المجموعات و يجب ان يكون العضو المهموس له موجود في نفس المجموعة\nماذا تنتظر جربهُ الان 😉"
};

let en = {
    "about": "About",
    "aboutMsg": "%credit%\nThank you for your excellent work and your support. You have really made my life more comfortable and have taken my worries away. \n This bot made by @rrbot . \n /start - to go back to the main page.",
    "title1": "🔒 A whisper message to ",
    "title2": ", Only he/she can open it.",
    "showMsg": "show message 🔐",
    "missingInfo": "write target's @username or id at the end of your message",
    "missingMessage": "Message not available :(",
    "mismatchMessageRecipient": "nice Try ...",
    "howToUseButton": "Learn more ...",
    "switch_pm_text": "Learn how to send whispers",
    "switch_inline_query": "hello @abdood",
    "howToNoUsername": "Send whispers to a user without username.",
    "notToU": "Sorry, you can't see this whisper because it was not sent to you 🔒.",
    "description": "Message format should be like \n@nnbbot your message @username",
    "description2": " he/she only can open it.",
    "queryTooLong": "Whisper is too long 🤕",
    "queryTooLongDescription": "I'm sorry 🐤 \nthe maximum limit for whispers in Telegram is *200* character.",
    "startBtn": "Other ways 📝",
    "testItNow": "Send a whisper 💌",
    "testItNowInline": "\nHello, this is a whisper\n@abdood",
    "websiteLink": "deep explanation",
    "id": "user Id",
    "test": "hello 👀",
    "firstName": "First Name",
    "lastName": "Last Name",
    "username": "Username",
    "sendUsingId": "Send whisper using user Id",
    "sendUsingUsername": "Send whisper using username",
    "fwd": "Click the button below to send a whisper to this user",
    "dontFwdChannel": "This message is forwarded from a channel!!\n you can't send whisper to channels \n forwarded message from user with you in the same group\n /start - learn how to send whispers",
    "noUsername": "\n🤔 How can I send whisper to someone who doesn't have username?\n\n💡 You can use the user's Id instead of username. the user Id works with all users even if they have a username\n\n🤔 Ok, what is the user Id?\n\n💡 A user Id is a unique number and every user in telegram has their own user Id\n\n🤔 How can I get the user Id to use it on this bot?\n\n💡 Simply forward any message from the user that you want to send a whisper to and I'll give you the user Id\n\n🤔 Ok now I have the user Id, how can I send a whisper to that user?\n\n💡 Its very simple, you only need to put the user Id at the end of your inline query as shown in this example\n\n`@nnbbot hello 12345678`\n\nthe number which is at the end of the query represent's the user Id\n\nif you still have a problem click on the Button below.",
    "start": "Welcome: @x!\n🌐 I'm the Whisper Bot.\n\n💬 You can use me to send secret whispers in groups.\n\n🔮 I work in the Inline mode that means you can use me even if I'm not in the group.\n\n💌 It is very easy to use me, simply forward a message from a user to which you want to send a whisper and I'll do the rest for you.\n\nThere are other ways to use me too. If you are interested to learn more about me click on the Button below.\n------------\n[💎 for more useful bots click here 💎](https://t.me/+erdi3TX590hlNWVi)\n",
    "howToUse": "\nthe other way to use me is to write the inline query by your self\n\nthe format should be in this arrangement\n\n`@nnbbot your whisper @username`\n\nnow I'll split out the format in 3 parts and explain every part of it\n\n1- `@nnbbot`\nthis is my username it *should* be at the beginning of the inline query so I'll know that you are using me and not another bot.\n\n2-`whisper message`\nit is the whisper that will be sent to the target user, you need to remove `your whisper` and insert your actual whisper.\n\n3- `@username`\nyou should replace this with target's username so the bot will know that the user with this username can see your `whisper message`.\n\nexample:- \n`@nnbbot hello this is a test @abdood`\n\n📎 the bot works in groups and the target user should be in the same group with you\nwhat you are waiting for?!\ntry me now 😉\n"
};

let fa = {
    "aboutMsg": "با تشکر ویژه از \n %credit%\n /start - منو اصلى",
    "about": "درباره",
    "title1": "🔒 یک نجوا به ",
    "title2": "، فقط ایشان می‌تواند آن را باز کند.",
    "showMsg": "نمایش پیام 🔐",
    "missingInfo": "@نام‌کاربری یا شناسه عددی کاربر مقصد را در انتهای پیام خود وارد کنید.",
    "missingMessage": "پیام مورد نظر موجود نیست :(",
    "mismatchMessageRecipient": "nice Try...",
    "howToUseButton": "بیش‌تر بدانید ...",
    "switch_pm_text": "یاد بگیرید که چطور نجوا ارسال کنید",
    "switch_inline_query": "سلام @adbos",
    "howToNoUsername": "چگونه به کاربری که نام کاربری ندارد نجوا بفرستیم",
    "notToU": "شرمنده، نمی‌توانید محتوای این نجوا را ببینید زیرا به شما ارسال نشده 🔒.",
    "description": "قالب پیام باید به صورت\n@nnbot @نام‌کاربری 'پیام شما'\nباشد.",
    "description2": "فقط ایشان می‌تواند بازش کند.",
    "queryTooLong": "پیام طولانی تر از حد مجاز است 🤕",
    "queryTooLongDescription": "متاسفانه 🐤 \nحداکثر طول مجاز برای نجوا ۲۰۰ حرف است.",
    "startBtn": "📝 راه‌های دیگر استفاده از من",
    "testItNow": "ارسال نجوا 💌",
    "testItNowInline": "\nسلام، این یک نجوا است\n@abdood",
    "websiteLink": "توضیحات کامل",
    "id": "شناسه کاربری عددی",
    "test": "👀 سلام",
    "firstName": "نام",
    "lastName": "نام خانوادگی",
    "username": "نام کاربری",
    "sendUsingId": "ارسال نجوا با استفاده از شناسه عددی کاربر",
    "sendUsingUsername": "ارسال نجوا با استفاده از نام کاربری",
    "fwd": "روی دکمه زیر کلیک کن تا به این کاربر پیام بفرستی",
    "dontFwdChannel": "این پیام از کانال ارسال شده!!\n شما نمی‌توانید به کانال نجوا ارسال کنید.\nپیامی را از کاربری که در گروه مشترک با شما قرار دارد ارسال کنید.\nstart - یاد بگیر چگونه نجوا بفرستی",
    "noUsername": "\n🤔 چطور می‌توانم به شخصی که نام کاربری ندارد نجوا ارسال کنم؟\n\n💡 شما می‌توانید به جای نام کاربری شناسه عددی را ارسال کنید. استفاده از شناسه عددی برای تمامی کاربران ممکن است حتی اگر نام کاربری نداشته باشند.\n\n🤔 خیلی خب، شناسه عددی چیست؟\n\n💡 شناسه عددی، یک عدد است که برای هر کاربری یکتاست. هر کاربری در تلگرام شناسه عددی منحصر بفرد دارد.\n\n🤔 چگونه می‌توانم شناسه عددی کاربری را در این ربات مورد استفاده قرار دهم؟\n\n💡 صرفا کافیست پیامی از کاربر مورد نظرتان را به ربات ارسال کنید تا من شناسه عددی او را به شما بدهم.\n\n🤔 خب حالا من با این شناسه عددی چطور می‌توانم به آن کاربر پیام بفرستم؟\n\n💡 خیلی ساده است، کافیست شناسه عددی او را در انتهای دستور درون‌خط (اینلاین) خود قرار دهید. مانند نمونه زیر:\n\n`@nnbbot salam 12345678`\n\nهمانطور که می‌بینید عددی که در انتهای دستور است شناسه عددی کاربر می‌باشد.\n\nاگر هنوز مشکلی دارید بر روی دکمه‌ی زیر کلیک کنید.",
    "start": "خوش آمدی: @x!\n🌐 من ربات نجوا هستم.\n\n💬 شما می‌توانید با استفاده از من در داخل گروه‌ها نجوا ارسال کنید.\n\n🔮 من به صورت \"از راه دور\" کار می‌کنم، یعنی حتی اگر داخل گروهی نباشم همچنان می‌توانید از من استفاده کنید.\n\n💌 راه بسیار ساده استفاده از من بدین صورت است که پیامی از کاربری که می‌خواهید به ایشان نجوا ارسال کنید را برای من بفرستید و باقیش را بر عهده من بگذارید.\n\nراه‌های دیگری برای استفاده از من وجود دارد. برای فهمیدن آن‌ها روی دکمه زیر کلیک کنید.\n-------------------\n[💎 برای امتحان ربات‌های مفید دیگر کلیک کنید 💎](https://t.me/+erdi3TX590hlNWVi)\n",
    "howToUse": "\nنحوه دیگر استفاده از من، نوشتن دستور درون‌خط (اینلاین) توسط خود شماست\n\nقالب دستور باید به ترتیب زیر باشد\n\n`@nnbbot پیام نجوای شما @username`\n\nاکنون من قالب را به سه قسمت تقسیم کرده و هرکدام را جداگانه توضیح می‌دهم\n\na- `@nnbbot`\nاین نام کاربری من است و *باید* در ابتدای دستور درون خط باشد تا من بفهمم شما قصد استفاده از من را دارید.\n\nb-`پیام نجوای شما`\nاین نجوایی‌ست که به کاربر مقصد ارسال خواهد شد.شما باید  `پیام نجوای شما` را حذف کرده و پپام خود را جایگزین کنید.\n\nc- `@username`\nشما باید این را با نام کاربری کاربر مقصد جایگزین کنید تا ربات آن کاربر را پیدا کند و ایشان بتواند `پیام نجوا`ی شما را ببیند.\n\nمثال:- \n`@nnbbot سلام آزمایش می‌کنیم... @abdood`\n\n📎 ربات در گروه‌ها کار می‌کند و حتما کاربر مقصد باید در همان گروهی که شما حضور دارید حضور داشته باشد.\nمنتظر چه هستی!؟\nهمین الان من را امتحان کن 😉\n"
};

let it = {
    "about": "Info",
    "aboutMsg": "%credit%\nSi ringraziano per il loro eccelente lavoro e supporto. Avete reso la mia vita migliore. \n Questo bot è stato fatto da @rrbot . \n /start - Torna alla pagina principale.",
    "title1": "🔒 Messaggio per ",
    "title2": ", solo lui/lei lo potrà aprire.",
    "showMsg": "Mostra il messaggio 🔐",
    "missingInfo": "Scrivi il suo @username o l'id alla fine del tuo messaggio",
    "missingMessage": "Messaggio non più disponibile :(",
    "mismatchMessageRecipient": "Bel tentativo...",
    "howToUseButton": "Leggi di più ...",
    "switch_pm_text": "Impara come mandare un messaggio",
    "switch_inline_query": "Ciao @abdood",
    "howToNoUsername": "Manda a qualcuno senza username.",
    "notToU": "Spiacenti, non puoi vedere questo messaggio, siccome non è diretto a te 🔒.",
    "description": "Il formato del messaggio deve essere \n@nnbbot 'Il tuo messaggio' @username",
    "description2": " solo lui/lei lo potrà aprire",
    "queryTooLong": "Il messaggio è troppo lungo 🤕",
    "queryTooLongDescription": "Mi dispiace 🐤\nMassimo 200 caratteri per messaggio.",
    "startBtn": "Altri modi 📝",
    "testItNow": "Manda un messaggio 💌",
    "testItNowInline": "\nCiao, questo è un messaggio\n@abdood",
    "websiteLink": "Spiegazione approfondita",
    "id": "Id utente",
    "test": "ciao 👀",
    "firstName": "Nome",
    "lastName": "Cognome",
    "username": "Username",
    "sendUsingId": "Manda un messaggio usando l'Id del utente",
    "sendUsingUsername": "Manda un messaggio usando lo username",
    "fwd": "Premi il bottone per mandare il messaggio a questo utente",
    "dontFwdChannel": "questo messaggio è inoltrato da un canale!!\n non puoi mandare messaggi ai canali \n Inoltra un messaggio da un utente del tuo stesso gruppo\n /start - Impara come mandare messaggi",
    "noUsername": "\n🤔 Come posso mandare un messaggio a qualcuno che non ha l'username?\n\n💡 Puoi usare l'Id dell'utente invece del suo username, esso funzionerà sempre, anche se non ha uno username\n\n🤔 Ok, cos'è l'Id dell'utente?\n\n💡 L'Id dell'utente è un numero univoco, ogni utente di Telegram ha il proprio\n\n🤔 Come posso prendere un Id di un utente per usarlo in questo bot?\n\n💡 Semplicemente inoltrando qualsiasi messaggio dalla persona a cui vuoi mandare un messaggio, e io ti darò il suo Id utente\n\n🤔 Ok, ora ho il suo Id utente, come posso mandargli/le un messaggio?\n\n💡 È molto semplice, hai solo bisogno di mettere l'Id utente alla fine della tua inline query come mostrato in questo esempio\n\n`@nnbbot ciao 12345678`\n\nIl numero alla fine rappresenta l'Id utente\n\nSe continui ad avere problemi, clicca il bottone qui sotto.",
    "start": "Benvenuto: @x!\n🌐 Sono Whisper Bot.\n\n💬 Puoi usarmi per mandare messaggi segreti nei gruppi.\n\n🔮 Funziono nella modalità inline, ciò significa che puoi usarmi anche se non sono nel gruppo.\n\n💌 È molto semplice usarmi, inoltrami un messaggio dell'utente a cui vuoi mandare un messaggio ed io farò il resto per te.\n\nCi sono altri modi per usarmi. Se sei interessato a leggere di più su di me, clicca il bottone qua sotto.\n------------\n",
    "howToUse": "\nUn altro modo per usarmi è di scriverti l'inline query da solo\n\nIl formato dovrà essere in questo modo\n\n`@nnbbot il tuo messaggio @username`\n\nOra lo dividerò in tre parti e te le spiegherò\n\n1- `@nnbbot`\nQuesto è il mio username e *deve* essere all'inizio dell'inline query, così saprò che stai usando me e non un altro bot.\n\n2-`il tuo messaggio`\nQuesto è il messaggio che verrà spedito al destinatario, dovrai togliere `il tuo messaggio` e inserire il tuo vero messaggio.\n\n3- `@username`\nDevi sostituirlo con L'username del destinatario, così il bot saprà a chi stai mandando il messaggio; il destinatario vedrà `il tuo messaggio`.\n\nEsempio:- \n`@nnbbot ciao, questo è un test @username`\n\n📎 Il bot funziona nei gruppi e il destinatario dovrà essere nello stesso gruppo con te\nCosa stai aspettando?!\nProvami 😉\n"
};

let de = {
    "about": "Info",
    "aboutMsg": "%credit%\nVielen Dank für eure ausgezeichnete Arbeit und eure Unterstützung. Ihr habt mein Leben wirklich komfortabler gemacht und mir meine Sorgen genommen.  \n Dieser Bot wurde von @rrbot erstellt. \n /start - um zur Hauptseite zurückzukehren.",
    "description": "Das Nachrichtenformat sollte wie folgt aussehen: \n@nnbbot 'Deine Nachricht' @Benutzername",
    "description2": " nur er/sie kann sie öffnen.",
    "dontFwdChannel": "Diese Nachricht wird von einem Kanal weitergeleitet!!\n Du kannst keine Flüsternachricht an Kanäle senden \n weitergeleitete Nachricht von einem Benutzer, der mit Dir in der gleichen Gruppe ist\n /start - erfahre, wie man Flüsternachrichten verschickt",
    "firstName": "Vorname",
    "fwd": "Klicke auf die Schaltfläche, um dem Benutzer eine Nachricht zu senden",
    "howToNoUsername": "Nachricht einem Nutzer ohne Benutzernamen senden",
    "howToUse": "\nEine weitere Möglichkeit, mich zu benutzen, besteht darin, die Inline-Abfrage selbst zu schreiben\n\nDie Formatierung sollte wie folgt aussehen\n\n`@nnbbot Deine Flüsternachricht @Benutzername`\n\nNun werde ich das Dateiformat in 3 Teile aufteilen und jeden Teil davon erklären\n\n1- `@nnbbot`\ndies ist mein Benutzername, er *sollte* am Anfang der Inline-Abfrage stehen, damit ich weiß, dass Du mich und nicht einen anderen Bot verwendest.\n\n2-`Flüsternachricht`\nDies ist die Flüsternachricht, die an den Zielbenutzer gesendet wird. Du musst `Deine Flüsternachricht`entfernen und Deine eigentliche Nachricht einfügen.\n\n3- `@Benutzername`\nDieser ist durch den Benutzernamen der Zielperson zu ersetzen, damit der Bot weiß, dass der Empfänger Deine`Flüsternachricht` mit diesem Benutzernamen sehen kann.\n\nBeispiel:\n`@nnbbot Hallo, dies ist ein Test @abdood`\n\n📎 der Bot funktioniert in Gruppen und der Zielbenutzer sollte mit Dir in derselben Gruppe sein\nWorauf wartest Du noch?!\nTeste mich jetzt gleich 😉\n",
    "howToUseButton": "Mehr erfahren ...",
    "id": "Benutzer-ID",
    "lastName": "Nachname",
    "mismatchMessageRecipient": "Netter Versuch ...",
    "missingInfo": "schreibe Benutzernamen oder Empfänger-ID am Ende deiner Nachricht.",
    "missingMessage": "Nachricht nicht verfügbar :(",
    "noUsername": "\n🤔 Wie kann ich Flüsternachrichten an jemanden senden, der keinen Benutzernamen hat?\n\n💡 Anstelle des Benutzernamens kann auch die Benutzer-ID des Benutzers verwendet werden. Die Benutzer-ID funktioniert mit allen Teilnehmern, auch wenn sie keinen Benutzernamen haben.\n\n🤔 Ok, was ist die Benutzer-ID?\n\n💡 Eine Nutzer-ID ist eine eindeutige Nummer: jeder Telegram-Benutzer hat seine persönliche Nutzer-ID.\n\n🤔 Wie kann ich die Nutzer-ID erhalten, um sie in diesem Bot zu nutzen?\n\n💡 Leite einfach irgendeine Nachricht jenes Teilnehmers, dem du ein „Geheimnis“ zuflüstern möchtest, an mich weiter und ich verrate dir seine User-ID.\n\n🤔 Ok, jetzt habe ich die Nutzer-ID, wie kann ich diesem Benutzer eine „Flüsternachricht“ senden?\n\n💡 Das ist ganz einfach, Du brauchst nur die User-ID, wie im folgendem Beispiel, an das Ende Deiner Inline-Abfrage zu setzen:\n\n`@nnbbot Hello 12345678`\n\nDie Zahl am Ende steht für die Nutzer-ID.\n\nWenn Du damit nicht zurechtkommen solltest, klicke einfach auf die Schaltfläche hier unten.",
    "notToU": "Nachricht kann leider nicht angezeigt werden, da sie nicht an Dich gerichtet ist 🔒.",
    "queryTooLong": "Die Nachricht ist zu lang 🤕",
    "queryTooLongDescription": "Tut mir leid 🐤\nDie maximale Länge für Flüsternachrichten beträgt *200* Zeichen.",
    "sendUsingId": "Nachricht mit Benutzer-ID senden",
    "sendUsingUsername": "Nachricht mit Benutzername senden",
    "showMsg": "Nachricht anzeigen 🔐",
    "start": "Herzlich willkommen: @x!\n🌐 Ich bin der Flüsterbot.\n\n💬 Du kannst mich benutzen, um geheime Flüsternachrichten in Gruppen zu versenden.\n\n🔮 Ich arbeite im Inline-Modus, d.h. Du kannst mich benutzen, auch wenn ich nicht in der Gruppe bin.\n\n💌 Es ist sehr einfach, mich zu benutzen, leite einfach eine Nachricht von jenem Benutzer an mich weiter, dem Du ein Geheimnis zuflüstern möchtest, und ich erledige den Rest für Dich.\n\nEs gibt auch andere Möglichkeiten, mich zu benutzen. Wenn Du daran interessiert bist, mehr über mich zu erfahren, klicke auf die Schaltfläche hier unten.\n------------\n[💎 für weitere nützliche Bots klicke bitte hier 💎](https://t.me/+erdi3TX590hlNWVi)\n",
    "startBtn": "Weitere Methoden 📝",
    "switch_inline_query": "Hallo @abdood",
    "switch_pm_text": "Lerne, Nachrichten zu verschicken",
    "test": "Hallo 👀",
    "testItNow": "Sende eine Nachricht 💌",
    "testItNowInline": "\nHallo, dies ist eine Flüsternachricht\n@abdood",
    "title1": "🔒 Nachricht an ",
    "title2": ", nur er/sie kann sie öffnen.",
    "username": "Benutzername",
    "websiteLink": "Ausführliche Erklärung"
}

let ku = {
    "about": "دەربارە",
    "aboutMsg": "زۆر سوپاس بۆ ئەوانەی یارمەتیان دام ئەم بۆتە تەواو بکەم.\n\n%credit%\n\n داڕێژەری بۆت:  @rrbot \n /start -  گەڕانەوە بۆ پەڕەی سەرەکی",
    "description": "داڕشتی چرپەنامە دەبێت وا بێت \n@nnbbot چرپەی تۆ @username",
    "description2": "تەنیا ئەو دەتوانێت نامەکە بکاتەوە.",
    "dontFwdChannel": "ئەم نامە لە کەناڵەوە هاوردە کراوە!!\nچرپەنامە نانێردرێتە کەناڵەکان\nنامەی کەسێک هاوردە بکە کە لەگەڵ تۆ لە گرووپی هاوبەشدایە\n /start - چۆنیەتی ناردنی چرپەنامە فێر ببە",
    "firstName": "ناوی یەکەم",
    "fwd": "دووگمەی خوارەوە دابگرە بۆ ناردنی چرپەنامەیەک بۆ ئەم بەکارهێنەرە",
    "howToNoUsername": "چۆن چرپە بنێمە کەسێک کە ناوی بەکارهێنەری نییە",
    "howToUse": "ڕێگای تر بۆ بەکارهێنانم، نووسینی فرمانی ناو-هێڵە لەلایەن تۆەوە\n\nداڕشتەکە دەبێت لەم ڕێکخستنەدا بێت\n\n\" @nnbbot چرپەی تۆ @username \"\n\nئێستا داڕشتەکە لە 3 بەش جیادەکەمەوە و هەموو بەشێکی شی دەکەمەوە.\n\n1- ' @nnbbot '\nئەمە ناوی بەکارهێنەری منە و دەبێت لە سەرەتای فرمانی ناو-هێڵدا بێت بۆ ئەوەی من بزانم کە تۆ من بەکاردێنیت نەک بۆتێکی تر.\n\n2- ' چرپەی تۆ '\nئەو چرپەنامەیە کە بۆ بەکارهێنەری مەبەست دەنێردرێت، پێویستە 'چرپەی تۆ' لاببەیت و چرپە ڕاستەقینەکەت تێبکەیت.\n\n3- ' @username '\nپێویستە ئەمە بە ناوی بەکارهێنەری مەبەست جێگۆڕکێ بکەیت بۆ ئەوەی بۆت ئەو کەسە بدۆزێتەوە و ئەو کەسە بتوانێت چرپەنامەکەت ببینێت.\n\nنموونە:- \n@nnbbot سڵاو تاقی دەکەمەوە... @abdood\n\n📎 بۆتەکە لە گرووپەکاندا کار دەکات و دەبێت بەکارهێنەری مەبەست لە هەمان گرووپدا بێت کە تۆی تێدایە\n\nچاوەڕێی چی دەکەیت!؟\nهەر ئێستا تاقیم بکەوە 😉.",
    "howToUseButton": "زیاتر بزانە ...",
    "id": "پێناسەی بەکارهێنەر",
    "lastName": "پاشناو",
    "mismatchMessageRecipient": "هەوڵێکی چاک ...",
    "missingInfo": "لە کۆتایی نامەکەدا ناوی بەکارهێنەری یان پێناسەی کەسی مەبەست بنووسە.",
    "missingMessage": "نامەکە لە بەردەستدا نییە :(",
    "noUsername": "🤔 چۆن بتوانم چرپە بنێمە کەسێک کە ناوی بەکارهێنەری نەبێت؟\n\n💡 دەتوانی لەجیاتی ناوی بەکارهێنەری پێناسەی بەکارهێنەر بەکاربێنیت. پێناسەی بەکارهێنەر کاردەکات لەگەڵ هەموو بەکارهێنەرەکان تەنانەت ئەوانە وا ناوی بەکارهێنەریان هەیە\n\n🤔 باشە، پێناسەی بەکارهێنەر چییە؟\n\n💡 پێناسەی بەکارهێنەر ژمارەیەکی تایبەتییە و هەموو بەکارهێنەرێک لە تێلیگرامدا پێناسەی بەکارهێنەری خۆی هەیە\n\n🤔 چۆن دەتوانم پێناسەی بەکارهێنەر بەدەست بخەم بۆ بەکارهێنانی لەسەر ئەم بۆتە؟\n\n💡 بەس نامەیەکی ئەو کەسەی وا دەتەوێت، هاوردەی بۆت بکە بۆ ئەوەی پێناسەی ژمارەیی ئەو بەکارهێنەرت پێبدەم.\n\n🤔 ئێستا پێناسەی بەکارهێنەرم هەیە، چۆن دەتوانم چرپەیەک بۆ ئەو بەکارهێنەرە بنێم؟\n\n💡 زۆر سادەیە، تەنها پێویستە پێناسەی بەکارهێنەر بخەیتە کۆتایی داڕشتەکەوە وەک لەم نمونەیەدا پیشان دراوە\n\n@nnbbot slaw 12345678\n\nئەو ژمارەیەی کە لە کۆتایی داڕشتەکەدایە پێناسەی ژمارەیی بەکارهێنەرە.\n\nئەگەر هێشتاش کێشەت هەیە کرتە لەسەر دوگمەی خوارەوە بکە.",
    "notToU": "بەداخەوە، تۆ ناتوانی ناوەڕۆکی ئەم چرپەنامە ببینی چونکە بۆ تۆ نەنێردراوە،🔒.",
    "queryTooLong": "چرپەنامەکە ئێجگار درێژە 🤕",
    "queryTooLongDescription": "ببوورە 🐤 \nئەوپەڕی درێژی چرپەنامەی تەلەگرام *200* کارەکتەرە.",
    "sendUsingId": "ناردنی چرپەنامە بە بەکارهێنانی پێناسەی بەکارهێنەر",
    "sendUsingUsername": "ناردنی چرپەنامە بە بەکارهێنانی ناوی بەکارهێنەری",
    "showMsg": "پیشاندانی نامە 🔐",
    "start": "بەخێربیت: @x!\n🌐 من بۆتی چرپاندنم\n\n💬 دەتوانی بەهۆی منەوە بە نهێنی لەناو گرووپەکان بچرپێنی.\n\n🔮 من بە شێوازی ناو-هێڵ کاردەکەم واتە دەتوانی بەکارم بهێنیت تەنانەت ئەگەر لەناو گرووپەکەشدا نەبم.\n\n💌 چۆنیەتی بەکارهێنانم زۆر ئاسانە، دەبێت نامەیەکی ئەو کەسەی کە دەتەوێت چرپەی بۆ بنێری هاوردەی ئێرەی بکەی و ئەویتری خۆم دەیکەم.\n\nچەندین ڕێگەی تریش هەیە بۆ بەکارهێنانم. ئەگەر حەز دەکەی فێریان بی ئەوە کرتە لەسەر دووگمەی خوارەوە بکە.\n------------\n[💎 ئێرە دابگرە بۆ چەندەها بۆتی سوودبەخشی تر 💎](https://t.me/+erdi3TX590hlNWVi)",
    "startBtn": "ڕێگەکانی تری بەکارهێنانم 📝",
    "switch_inline_query": "سڵاو @abdood",
    "switch_pm_text": "چۆنیەتی ناردنی چرپەنامە فێر ببە",
    "test": "سڵاو 👀",
    "testItNow": "چرپەنامەیەک بنێرە 💌",
    "testItNowInline": "سڵاو، ئەمە چرپەنامەیە\n@abdood",
    "title1": "🔒 چرپەنامەیەک بۆ ",
    "title2": "، تەنیا ئەو دەتوانێت نامەکە بکاتەوە",
    "username": "ناوی بەکارهێنەری",
    "websiteLink": "ڕوونکردنەوەی قووڵ",
}

let fr = {
    "about": "A propos",
    "aboutMsg": "%credit%\nMerci pour votre excellent travail et votre soutien. Vous m'avez vraiment simplifié la vie en m'enlevant bien des soucis.\nCe bot a été développé par @rrbot.\n/start - pour revenir à la page principale.",
    "description": "Le format du message doit ressembler à \n@nnbbot votre message @username",
    "description2": " seul cette personne pourra l'afficher.",
    "dontFwdChannel": "ce message est transféré depuis un canal !!\n vous ne pouvez pas envoyer de messages dans les canaux\n Transférez des messages d'utilisateur venant des groupes communs\n /start - apprendre à envoyer des messages",
    "firstName": "Nom",
    "fwd": "Appuyez sur le bouton pour envoyer le message à cet utilisateur",
    "howToNoUsername": "Envoyer à quelqu'un sans nom d'utilisateur.",
    "howToUse": "\nune autre façon de m'utiliser est d'écrire une requête inline vous-même\n\nle format doit correspondre à ceci\n`@nnbbot votre message @username`\n\nje vais diviser le format en 3 parties et les expliquer\n\n1- `@nnbbot`\nest mon nom d'utilisateur, il *doit* être au début de la requête inline pour que je sache que vous m'utilisez moi et pas un autre bot.\n\n2-`votre message`\nest message qui sera envoyé à l'utilisateur cible, vous devez supprimer `votre message` et insérer votre réel message.\n\n3- `@username`\ndoit être remplacé par le nom d'utilisateur du destinataire afin que le bot sache qui peut voir ce `message secret`.\nexemple:- \n`@nnbbot bonjour ceci est un test @abdood`\n\n📎 le bot fonctionne dans les groupes, si le destinataire y est également présent, qu'attendez-vous ?! Essayez-moi maintenant 😉\n",
    "howToUseButton": "En savoir plus...",
    "id": "ID utilisateur",
    "lastName": "Prénom",
    "mismatchMessageRecipient": "bien essayé...",
    "missingInfo": "Ecrivez son @username ou son ID à la fin de votre message",
    "missingMessage": "Message non disponible :(",
    "noUsername": "\n🤔 Comment envoyer un message à quelqu'un qui n'a pas de nom d'utilisateur ?\n\n💡 Vous pouvez utiliser son ID au lieu du nom d'utilisateur. Les ID fonctionnent avec tous les utilisateurs même s'ils ont un nom d'utilisateur.\n\n🤔 D'accord mais qu'es qu'un ID ?\n\n💡 Un ID est un numéro unique lié à chaque compte Telegram\n\n🤔 Comment obtenir un ID pour l'utiliser sur ce bot ?\n\n💡 Transférez-moi simplement un message de l'utilisateur auquel vous souhaitez envoyer un message et je vous donnerai son ID\n\n🤔 Ok maintenant que j'ai l'ID, comment puis-je envoyer un message à cet utilisateur ?\n\n💡 C'est très simple, il vous suffit de mettre l'ID à la fin de votre commande, comme indiqué dans cet exemple\n\n`@nnbbot Salut 12345678`\n\nle nombre qui est à la fin correspond à son ID\n\nsi vous avez toujours un problème, cliquez sur le bouton ci-dessous.",
    "notToU": "Désolé, vous ne pouvez pas voir ce message car il ne vous est pas destiné 🔒.",
    "queryTooLong": "Message trop long 🤕",
    "queryTooLongDescription": "Je suis désolé 🐤\nla limite maximale est de *200* caractères.",
    "sendUsingId": "Envoyer un message via un ID",
    "sendUsingUsername": "Envoyer un message via un nom d'utilisateur",
    "showMsg": "Afficher le message 🔐",
    "start": "Bienvenue @x !\n🌐 Je suis Whisper Bot.\n\n💬 Vous pouvez m'utiliser pour envoyer des messages secrets dans les groupes.\n\n🔮 Je travaille en mode intégré (inline), ce qui signifie que vous pouvez m'utiliser même si je ne suis pas dans le groupe.\n\n💌 C'est simple de m'utiliser, il suffit de me transférer le message d'un utilisateur auquel vous souhaitez envoyer le message secret et je m'occuperai du reste.\n\nIl existe d'autres méthodes pour m'utiliser. Pour en savoir plus, cliquez sur le bouton ci-dessous.\n------------\n[💎 Pour d'autres bots utiles, cliquez ici 💎](https://t.me/+erdi3TX590hlNWVi)\n",
    "startBtn": "Autres méthodes 📝",
    "switch_inline_query": "Bonjour @abdood",
    "switch_pm_text": "Apprenez à envoyer des messages",
    "test": "Salut 👀",
    "testItNow": "Envoyer un message 💌",
    "testItNowInline": "\nBonjour, c'est un message privé\n@abdood",
    "title1": "🔒 Message destiné à ",
    "title2": ", seul cette personne peut le visualiser.",
    "username": "Nom d'utilisateur",
    "websiteLink": "explication détaillées",
};

let ru = {
        "about": "Информация",
        "aboutMsg": "%credit%\nСпасибо за отличную работу и поддержку. Вы действительно сделали мою жизнь более комфортной и избавили меня от забот. \n Этот бот сделан @rrbot. \n /start - чтобы вернуться на главную страницу.",
        "title1": "🔒 Прошептанное сообщение ",
        "title2": ", Только он/она может открыть его.",
        "showMsg": "показать сообщение 🔐",
        "missingInfo": "напишите @username или id цели в конце сообщение",
        "missingMessage": "Сообщение недоступно :(",
        "mismatchMessageRecipient": "хорошая попытка ...",
        "howToUseButton": "Учить больше ...",
        "switch_pm_text": "Узнайте, как отправлять шепот",
        "switch_inline_query": "Привет @abdood",
        "howToNoUsername": "Отправлять шепотом пользователю без имени пользователя.",
        "notToU": "Извините, вы не видите этот шепот, потому что он был отправлен не вам 🔒.",
        "description": "Формат сообщение должен быть похож на \n@nnbbot ваше сообщение @username",
        "description2": " только он/она может его открыть.",
        "queryTooLong": "Шепот слишком длинный 🤕",
        "queryTooLongDescription": "мне жаль 🐤 \nМаксимальный лимит для шепота в Telegram - *200* символов.",
        "startBtn": "Другие способы 📝",
        "testItNow": "Отправить шепотом 💌",
        "testItNowInline": "\nПривет, это шепот\n@abdood",
        "websiteLink": "глубокое объяснение",
        "id": "ID пользователя",
        "test": "Привет 👀",
        "firstName": "Имя",
        "lastName": "Фамилия",
        "username": "Юзернейм",
        "sendUsingId": "Отправить шепотом с использованием идентификатора пользователя",
        "sendUsingUsername": "Отправить шепотом, используя имя пользователя",
        "fwd": "Нажмите кнопку ниже, чтобы отправить этому пользователю шепот",
        "dontFwdChannel": "Это сообщение пересылается с канала!!\n вы не можете отправлять шепотом на каналы \n переадресованное сообщение от пользователя, находящегося с вами в одной группе\n /start - узнайте, как отправлять шепотом",
        "noUsername": "\n🤔 Как я могу отправить шепот кому-то, у кого нет имени пользователя?\n\n💡 Вы можете использовать ID пользователя вместо имени пользователя. ID пользователя работает со всеми пользователями, даже если у них есть имя пользователя\n\n🤔 Хорошо, каков идентификатор пользователя?\n\n💡 Идентификатор пользователя - это уникальный номер, и каждый пользователь в Telegram имеет свой собственный идентификатор пользователя\n\n🤔 Как я могу получить идентификатор пользователя, чтобы использовать его на этом боте?n\n💡 Просто перешлите любое сообщение от пользователя, которому вы хотите отправить шепот, и я дам вам идентификатор пользователя\n\n🤔 Хорошо, теперь у меня есть идентификатор пользователя, как я могу отправить шепот этому пользователю?\n\n💡 Это очень просто, вам нужно только указать идентификатор пользователя в конце вашего встроенного запроса, как показано в этом примере\n\n@nnbbot hello 12345678\n\nчисло в конце запроса представляет идентификатор пользователя\n\если у вас все еще есть проблема, нажмите кнопку ниже.",
        "start": "Добро пожаловать: @x!\n🌐 Я шепот-бот.\n\n💬 Вы можете использовать меня, чтобы отправлять секретные сообщения в группах.\n\n🔮 Я работаю в режиме Inline, что означает, что вы можете использовать меня, даже если Я не в группе.\n\n💌 Меня очень легко использовать, просто пересылайте сообщение от пользователя, которому вы хотите отправить шепот, а я сделаю все остальное за вас.\n\nесть и другие способы использовать меня тоже. Если вам интересно узнать обо мне больше, нажмите кнопку ниже.\n------------\n[💎 чтобы узнать о других полезных ботах, нажмите здесь 💎](https://t.me/+erdi3TX590hlNWVi)\n",
        "howToUse": "\nдругой способ использовать меня - написать встроенный запрос в одиночестве\n\nформат должен быть таким\n\n@nnbbot ваш шепот @username\n\nТеперь я разделю формат на 3 части и объясните каждую его часть\n\n1- @nnbbot\nэто мое имя пользователя, оно *должно* быть в начале встроенного запроса, чтобы я знал, что вы используете меня, а не другого бота.\n\n2-шепотом message\nit - это шепот, который будет отправлен целевому пользователю, вам нужно удалить свой шепот и вставить свой фактический шепот.\n\n3- @username\nвы должны заменить его на имя целевого пользователя, чтобы бот знал, что пользователь с этим именем пользователя можно увидеть ваше шепотное сообщение.\n\nпример: - \n@nnbbot привет, это тест @abdood\n\n📎 бот работает в группах, и целевой пользователь должен быть в одной группе с вами\nкак ты ждешь?!\ nпопробуйте меня сейчас 😉\n",
    }
;

let shared = {
    "ar": "عربي 🇵🇸",
    "en": "🇬🇧 English",
    "fa": "فارسى 🇮🇷",
    "fr": "🇫🇷 Français",
    "ru": "🇷🇺 Русский",
    "it": "🇮🇹 Italiano",
    "de": "🇩🇪 Deutsch",
    "ku": "کوردی 🇮🇶",
    "lang": "🇬🇧🇵🇸🇮🇷🇮🇹🇩🇪🇮🇶🇫🇷🇷🇺",
    "chooseLang": [
        "🇬🇧🇵🇸🇮🇷🇮🇹🇩🇪🇮🇶🇫🇷🇷🇺",
        "a- Choose your language.",
        "b- اختر لغتك.",
        "c- زبان خود را انتخاب کنید.",
        "d- Scegli la tua lingua.",
        "e- Wähle Deine Sprache.",
        "f- زمانەکەت هەڵبژێرە",
        "g- Choisissez votre langue",
        "h- Выберите свой язык.",
        "🇬🇧🇵🇸🇮🇷🇮🇹🇩🇪🇮🇶🇫🇷🇷🇺"
    ].join("\n"),
    "credits": [
        "🇮🇷 @bor691",
        "🇮🇹 @davtur19",
        "🇩🇪 @wolfgangDECARLI",
        "🇮🇶 @RazhuyWruzhaw",
        "🇫🇷 @Flybrow",
        "🇷🇺 @esumo",
        "@preco21",
    ].join(" - "),
}

module.exports = {
    ar
    , en
    , fa
    , it
    , de
    , ku
    , fr
    , ru
};

for (let lang of Object.keys(module.exports)) {
    Object.assign(module.exports[lang], shared)
}
